### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tbranyen** [nodegit/nodegit#177]
WIP Refactor Descriptor:
- [x] Create accurate TypeMap for C, C++, JavaScript, and Emscripten.
- [x] Get access to struct information to finish `git_tree_entry`.
- [x] Clean up `generate/*` files.
- [x] All pre-existing tests should pass.

Future branches:
- [x] Introduce code coverage and better test analysis.
- [x] Prebuilt binaries.
- [x] Remove docs (also from gitignore).
- [x] Mocha / Istanbul test suite integration.
- [x] Move index.js to lib/nodegit.js.
