### ISSUE TITLE
Next release checklist

### ISSUE THREAD

**Issue by tbranyen** [nodegit/nodegit#256]
- [x] Update scripts in example folder.
- [x] Changelog and migration notes.
- [x] Ensure all existing tests are passing (no skips allowed).

... I'll update this when I think of more things.  Feel free to comment if you think I've missed something.
